import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { ThemeSwitch } from "@/components/ui/theme-switch";
import { cn } from "@/lib/utils";
import Text from "@/components/ui/text";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ribbit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(inter.className, "p-10 bg-neutral-50 dark:bg-zinc-950")}
      >
        <Providers>
          <header className="p-5 flex justify-between w-full border-b dark:border-zinc-800 mb-5">
            <Text variant="h1">Ribbit</Text>

            <ThemeSwitch />
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
